export * from './auth.service';
export * from './about.service';
export * from './course.service';
export * from './domain.service';
export * from './hero.service';
export * from './project.service';
export * from './testimonial.service';
export * from './techStack.service';
export * from './studyMaterial.service';
export * from './certificate.service';
export * from './careerImpact.service';
export * from './studentSuccess.service';
export * from './videoTestimonial.service';
export * from './trainerAbout.service';
export * from './notice.service';
export * from './module.service';
export * from './faq.service';
export * from './enrollCard.service';
export * from './enrollment.service'
export * from './youtubeShort.service'